### PR TITLE
Vanilla QHBM Baselines

### PR DESCRIPTION
**Pull request by sahilpatelsp**

### CODE REVIEW

**Comment by farice** [comment]
we should add an integration test so that we ensure that lib changes don't result in script breakages (at the least, that it can still run)

**Review by farice — CHANGES_REQUESTED** [review]

**Comment by farice** [comment]
can you delete the utils that are unused? and for the ones that are used i believe they can be found in the main lib

**Comment by farice** [comment]
can you mark this as ready for review as well?

**Comment by farice** [comment]
The todo should be a github issue that can be tackled in a later PR

**Review by farice — APPROVED** [review]

**Review by zaqqwerty — APPROVED** [review]
LGTM

**Pull request merged**
